import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';
import { radius } from '../theme/radius';
import { spacing } from '../theme/spacing';

export const restaurantDetailStyles = StyleSheet.create({
  container: {
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: colors.textSecondary,
    marginTop: spacing.md,
    fontSize: 14,
  },
  errorText: {
    color: colors.orange,
    fontSize: 16,
    marginBottom: spacing.xl,
  },
  retryButton: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: colors.gold,
    borderRadius: radius.sm,
  },
  retryButtonText: {
    color: colors.background,
    fontWeight: 'bold',
    fontSize: 14,
  },
  heroSection: {
    height: 280,
    backgroundColor: '#2D4356',
    position: 'relative',
    marginHorizontal: 0,
    marginBottom: spacing.xxl,
  },
  backButton: {
    position: 'absolute',
    top: 12,
    left: spacing.screen,
    zIndex: 10,
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: radius.round,
  },
  favoriteButton: {
    position: 'absolute',
    top: 12,
    right: spacing.screen,
    zIndex: 10,
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: radius.round,
  },
  logoContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logo: {
    width: 140,
    height: 140,
    borderRadius: radius.round,
    backgroundColor: '#1a2a3a',
    borderWidth: 4,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  logoFallback: {
    width: 140,
    height: 140,
    borderRadius: radius.round,
    backgroundColor: 'rgba(201, 169, 110, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(201, 169, 110, 0.3)',
  },
  contentSection: {
    paddingHorizontal: spacing.screen,
  },
  restaurantName: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: spacing.md,
  },
  badgesRow: {
    flexDirection: 'row',
    gap: spacing.xs,
    marginBottom: spacing.md,
    flexWrap: 'wrap',
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: 'rgba(201, 169, 110, 0.15)',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: 'rgba(201, 169, 110, 0.3)',
  },
  badgeOpen: {
    backgroundColor: 'rgba(76, 175, 80, 0.15)',
    borderColor: 'rgba(76, 175, 80, 0.3)',
  },
  badgeClosed: {
    backgroundColor: 'rgba(244, 67, 54, 0.15)',
    borderColor: 'rgba(244, 67, 54, 0.3)',
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: radius.round,
    backgroundColor: colors.error,
  },
  statusDotOpen: {
    backgroundColor: colors.success,
  },
  badgeText: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 12,
    fontWeight: '500',
  },
  badgePriceText: {
    color: colors.gold,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  starsContainer: {
    flexDirection: 'row',
  },
  ratingText: {
    color: colors.textPrimary,
    fontWeight: 'bold',
    fontSize: 14,
  },
  reviewCountText: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  description: {
    color: 'rgba(255, 255, 255, 0.75)',
    fontSize: 13,
    lineHeight: 20,
    marginBottom: spacing.xl,
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
    marginBottom: spacing.xxl,
  },
  infoCard: {
    flex: 1,
    minWidth: '48%',
    backgroundColor: colors.card,
    paddingHorizontal: spacing.md,
    paddingVertical: 14,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  infoLabel: {
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: '600',
    marginTop: spacing.sm,
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  infoValue: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
  },
  infoExtra: {
    color: colors.textSecondary,
    fontSize: 11,
    marginTop: 2,
  },
  menuSection: {
    marginBottom: spacing.xxl,
  },
  menuTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: spacing.md,
  },
  menuEmptyState: {
    alignItems: 'center',
    paddingVertical: 32,
    backgroundColor: 'rgba(201, 169, 110, 0.08)',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: 'rgba(201, 169, 110, 0.2)',
  },
  menuEmptyText: {
    color: colors.textSecondary,
    fontSize: 14,
    marginTop: spacing.md,
    textAlign: 'center',
  },
  menuText: {
    color: 'rgba(255, 255, 255, 0.75)',
    fontSize: 13,
    lineHeight: 20,
    backgroundColor: colors.card,
    padding: 14,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  menuItems: {
    gap: spacing.sm,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    gap: spacing.sm,
  },
  menuItemContent: {
    flex: 1,
  },
  menuItemName: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '500',
  },
  menuItemPrice: {
    color: colors.gold,
    fontSize: 12,
    fontWeight: 'bold',
  },
  menuUrlButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    backgroundColor: colors.gold,
    paddingVertical: 14,
    borderRadius: radius.sm,
  },
  menuUrlButtonText: {
    color: colors.background,
    fontSize: 14,
    fontWeight: 'bold',
  },
  reservationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    backgroundColor: colors.orange,
    paddingVertical: 14,
    borderRadius: radius.sm,
    marginBottom: spacing.md,
  },
  reservationButtonText: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: 'bold',
  },
  bottomSpacer: {
    height: spacing.screen,
  },
});
